# Generated by Django 5.2.6 on 2025-09-25 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consolas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companies',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.RenameField(
            model_name='consola',
            old_name='genero',
            new_name='empresa',
        ),
    ]
