# Generated by Django 5.2.6 on 2025-10-09 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consolas', '0002_alter_companies_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('pais_origen', models.CharField(max_length=100)),
                ('anio_salida', models.PositiveIntegerField(default=1990)),
                ('cantidad_consolas', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.AddField(
            model_name='consola',
            name='anio_salida',
            field=models.PositiveIntegerField(default=1990),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consola',
            name='juegos_vendidos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consola',
            name='ventas_totales',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='consola',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='consola',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolas', to='consolas.company'),
        ),
        migrations.DeleteModel(
            name='companies',
        ),
    ]
